// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiPrac.Data;

#nullable disable

namespace WebApiPrac.Migrations
{
    [DbContext(typeof(InvoiceDbContext))]
    [Migration("20250219102715_spGetCustomerByPage")]
    partial class spGetCustomerByPage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiPrac.Model.TblAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Address1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("AddressId")
                        .HasName("PK__tblAddre__091C2AFBDB2B92EE");

                    b.HasIndex("CustomerId");

                    b.ToTable("tblAddress", (string)null);
                });

            modelBuilder.Entity("WebApiPrac.Model.TblAncillary", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("AncillaryCost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("AncillaryName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__tblAncil__3214EC07A519FA4B");

                    b.ToTable("tblAncillary", (string)null);
                });

            modelBuilder.Entity("WebApiPrac.Model.TblArea", b =>
                {
                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("AreaName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CountryIdFk")
                        .HasColumnType("int")
                        .HasColumnName("CountryId_fk");

                    b.HasKey("AreaId")
                        .HasName("PK__tblArea__70B82048BA7BB70C");

                    b.HasIndex("CountryIdFk");

                    b.ToTable("tblArea", (string)null);
                });

            modelBuilder.Entity("WebApiPrac.Model.TblCountry", b =>
                {
                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CountryId")
                        .HasName("PK__tblCount__10D1609F1CC01FF9");

                    b.ToTable("tblCountry", (string)null);
                });

            modelBuilder.Entity("WebApiPrac.Model.TblCustomer", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("CustomerReferenceIdFk")
                        .HasColumnType("int")
                        .HasColumnName("CustomerReferenceId_fk");

                    b.Property<string>("CustomerSsn")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("CustomerSSN");

                    b.HasKey("CustomerId")
                        .HasName("PK__tblCusto__A4AE64D856F1D5D9");

                    b.ToTable("tblCustomer", (string)null);
                });

            modelBuilder.Entity("WebApiPrac.Model.TblGenuineCustomer", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("tblGenuineCustomer", (string)null);
                });

            modelBuilder.Entity("WebApiPrac.Model.TblModel", b =>
                {
                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryIdFk")
                        .HasColumnType("int")
                        .HasColumnName("CountryId_fk");

                    b.Property<string>("ManufacturerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModelBrand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ModelId")
                        .HasName("PK__tblModel__E8D7A12C8DC53E6B");

                    b.HasIndex("CountryIdFk");

                    b.ToTable("tblModel", (string)null);
                });

            modelBuilder.Entity("WebApiPrac.Model.TblProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProductCost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductId")
                        .HasName("PK__tblProdu__B40CC6CDB144643D");

                    b.ToTable("tblProduct", (string)null);
                });

            modelBuilder.Entity("WebApiPrac.Model.TblProductBackup", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProductCost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductId")
                        .HasName("PK__tblProdu__B40CC6CD23294279");

                    b.ToTable("tblProductBackup", (string)null);
                });

            modelBuilder.Entity("WebApiPrac.Model.TblProductCustomer", b =>
                {
                    b.Property<int>("ProductCustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("AncillaryIdFk")
                        .HasColumnType("int")
                        .HasColumnName("AncillaryId_fk");

                    b.Property<int?>("CustomerIdFk")
                        .HasColumnType("int")
                        .HasColumnName("CustomerId_fk");

                    b.Property<int?>("ModelIdFk")
                        .HasColumnType("int")
                        .HasColumnName("ModelId_fk");

                    b.Property<int?>("ProductIdFk")
                        .HasColumnType("int")
                        .HasColumnName("ProductId_fk");

                    b.Property<DateTime?>("SalesDate")
                        .HasColumnType("datetime");

                    b.HasKey("ProductCustomerId")
                        .HasName("PK__tblProdu__5D863CB9AD20AB41");

                    b.HasIndex("AncillaryIdFk");

                    b.HasIndex("CustomerIdFk");

                    b.HasIndex("ModelIdFk");

                    b.HasIndex("ProductIdFk");

                    b.ToTable("tblProductCustomer", (string)null);
                });

            modelBuilder.Entity("WebApiPrac.Model.TblAddress", b =>
                {
                    b.HasOne("WebApiPrac.Model.TblCustomer", "Customer")
                        .WithMany("TblAddresses")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__tblAddres__Custo__48CFD27E");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WebApiPrac.Model.TblArea", b =>
                {
                    b.HasOne("WebApiPrac.Model.TblCountry", "CountryIdFkNavigation")
                        .WithMany("TblAreas")
                        .HasForeignKey("CountryIdFk")
                        .HasConstraintName("FK__tblArea__Country__398D8EEE");

                    b.Navigation("CountryIdFkNavigation");
                });

            modelBuilder.Entity("WebApiPrac.Model.TblModel", b =>
                {
                    b.HasOne("WebApiPrac.Model.TblCountry", "CountryIdFkNavigation")
                        .WithMany("TblModels")
                        .HasForeignKey("CountryIdFk")
                        .HasConstraintName("FK__tblModel__Countr__3E52440B");

                    b.Navigation("CountryIdFkNavigation");
                });

            modelBuilder.Entity("WebApiPrac.Model.TblProductCustomer", b =>
                {
                    b.HasOne("WebApiPrac.Model.TblAncillary", "AncillaryIdFkNavigation")
                        .WithMany("TblProductCustomers")
                        .HasForeignKey("AncillaryIdFk")
                        .HasConstraintName("FK__tblProduc__Ancil__4E88ABD4");

                    b.HasOne("WebApiPrac.Model.TblCustomer", "CustomerIdFkNavigation")
                        .WithMany("TblProductCustomers")
                        .HasForeignKey("CustomerIdFk")
                        .HasConstraintName("FK__tblProduc__Custo__4BAC3F29");

                    b.HasOne("WebApiPrac.Model.TblModel", "ModelIdFkNavigation")
                        .WithMany("TblProductCustomers")
                        .HasForeignKey("ModelIdFk")
                        .HasConstraintName("FK__tblProduc__Model__4D94879B");

                    b.HasOne("WebApiPrac.Model.TblProduct", "ProductIdFkNavigation")
                        .WithMany("TblProductCustomers")
                        .HasForeignKey("ProductIdFk")
                        .HasConstraintName("FK__tblProduc__Prouc__4CA06362");

                    b.Navigation("AncillaryIdFkNavigation");

                    b.Navigation("CustomerIdFkNavigation");

                    b.Navigation("ModelIdFkNavigation");

                    b.Navigation("ProductIdFkNavigation");
                });

            modelBuilder.Entity("WebApiPrac.Model.TblAncillary", b =>
                {
                    b.Navigation("TblProductCustomers");
                });

            modelBuilder.Entity("WebApiPrac.Model.TblCountry", b =>
                {
                    b.Navigation("TblAreas");

                    b.Navigation("TblModels");
                });

            modelBuilder.Entity("WebApiPrac.Model.TblCustomer", b =>
                {
                    b.Navigation("TblAddresses");

                    b.Navigation("TblProductCustomers");
                });

            modelBuilder.Entity("WebApiPrac.Model.TblModel", b =>
                {
                    b.Navigation("TblProductCustomers");
                });

            modelBuilder.Entity("WebApiPrac.Model.TblProduct", b =>
                {
                    b.Navigation("TblProductCustomers");
                });
#pragma warning restore 612, 618
        }
    }
}
